# Project: 向群友介绍你的闪光点
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = 向群友介绍你的闪光点_private.res
OBJ      = 向群友介绍你的闪光点.o $(RES)
LINKOBJ  = 向群友介绍你的闪光点.o $(RES)
LIBS     = -L"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/lib" -L"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/include" -I"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"D:/Embarcadero/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = 向群友介绍你的闪光点.exe
CXXFLAGS = $(CXXINCS) -fexec-charset=GBK -finput-charset=UTF-8
CFLAGS   = $(INCS) -fexec-charset=GBK -finput-charset=UTF-8
DEL      = D:\Embarcadero\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

向群友介绍你的闪光点.o: 向群友介绍你的闪光点.cpp
	$(CPP) -c 向群友介绍你的闪光点.cpp -o 向群友介绍你的闪光点.o $(CXXFLAGS)

向群友介绍你的闪光点_private.res: 向群友介绍你的闪光点_private.rc 
	$(WINDRES) -i 向群友介绍你的闪光点_private.rc --input-format=rc -o 向群友介绍你的闪光点_private.res -O coff 

